"""Compatibility exports for the Loom resolution engine v3 package."""

from aoc_cli.resolution_v3 import (
    ACYCLIC_LAYERS,
    NORMAL,
    URGENT,
    ConstraintGraph,
    Edge,
    Engine,
    EngineStatus,
    Locus,
    LocusKind,
    Modality,
    Node,
    ProposalDecision,
    ProposalDecisionStatus,
    ProposalKind,
    Provenance,
    ResolutionProposal,
    Status,
    Worklist,
    canonicalize_proposals,
    copy_graph_for_proposal,
    reject_proposal,
    resolve,
    tarjan_scc,
)

__all__ = [
    "ACYCLIC_LAYERS",
    "NORMAL",
    "URGENT",
    "ConstraintGraph",
    "Edge",
    "Engine",
    "EngineStatus",
    "Locus",
    "LocusKind",
    "Modality",
    "Node",
    "ProposalDecision",
    "ProposalDecisionStatus",
    "ProposalKind",
    "Provenance",
    "ResolutionProposal",
    "Status",
    "Worklist",
    "canonicalize_proposals",
    "copy_graph_for_proposal",
    "reject_proposal",
    "resolve",
    "tarjan_scc",
]
