#!/usr/bin/env bash
# vault-brain-beat: periodic vault health check, linter pass, auto-promote pending, Current_Context update.
# Scheduled via Hermes cron every 240m (no_agent).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT"

VAULT="vaults/gaijinn-memory-fs"
STATE="$ROOT/.gaijinn/hermes-loop-state.json"
LOGFILE="$ROOT/.gaijinn/vault-brain-beat.log"

log() { echo "[$(date -u '+%Y-%m-%dT%H:%M:%SZ')] $*" >> "$LOGFILE"; }

log "START vault-brain-beat"

# 1. Run vault linter (knowledge_linter.py)
log "  → vault linter"
LINTER_ROOTS="$VAULT" python3 -m aoc_supervisor.knowledge_linter \
  --roots "$VAULT" \
  --exit-on-fail 2>>"$LOGFILE" && LINTER_OK=true || LINTER_OK=false
log "  linter pass: $LINTER_OK"

# 2. Auto-promote pending items
log "  → auto-promote pending"
gaijinn promote --yes 2>>"$LOGFILE" || log "  no pending promotions"

# 3. Health snapshot → Current_Context.md
log "  → update Current_Context.md"
CURRENT="$VAULT/10_Operations/Current_Context.md"
cat > "$CURRENT" << EOF
# Current Context — Vault Health Snapshot

*Generated by vault-brain-beat at $(date -u '+%Y-%m-%dT%H:%M:%SZ')*

- **Linter:** $([ "$LINTER_OK" = true ] && echo "PASS" || echo "FAIL")
- **Vault roots:** \`$VAULT\`
- **Convergence:** $(python3 -c "import json; s=json.load(open('$STATE')); print(s.get('convergence','unknown'))" 2>/dev/null || echo "unknown")
- **Phase:** $(python3 -c "import json; s=json.load(open('$STATE')); print(s.get('phase','unknown'))" 2>/dev/null || echo "unknown")
EOF

log "DONE vault-brain-beat (linter=$LINTER_OK)"
